-- MySQL Script generated by MySQL Workbench
-- 01/24/17 17:43:46
-- Model: New Model    vERSION: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- ---------------------------------------------------------
-- Schema dbsistemaLaravel
-- ---------------------------------------------------------

-- ---------------------------------------------------------
-- Schema dbsistemaLaravel
-- ---------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dblaravel` DEFAULT CHARACTER SET utf8;
USE `dblaravel`;